#ifndef LUNITY_CLIENT_RENDERER_MINECRAFT_MINECRAFTRENDERER_H
#define LUNITY_CLIENT_RENDERER_MINECRAFT_MINECRAFTRENDERER_H

#include "../Renderer.h"

class MinecraftRenderer : Renderer
{

};


#endif //LUNITY_CLIENT_RENDERER_MINECRAFT_MINECRAFTRENDERER_H
