#ifndef GUARD_ClientInstance
#define GUARD_ClientInstance
#include "../../Utils/Math.h"
#include "../../Utils/Utils.h"
#include "../../Mem/Mem.h"
#include "../../Utils/Nuv.h"
struct ClientInstance {
	/* Fields */
	char padding_168[160];
	class MinecraftGame* minecraftGame;
	char padding_208[32];
	class LoopbackPacketSender* loopbackPacketSender;
	char padding_320[104];
	class LocalPlayer* clientPlayer;
	char padding_1240[912];
	class GuiData* guiData;
	/* Virtuals */
	virtual void virt_pad_0() {};
	virtual void virt_pad_1() {};
	virtual void virt_pad_2() {};
	virtual void virt_pad_3() {};
	virtual void virt_pad_4() {};
	virtual void virt_pad_5() {};
	virtual void virt_pad_6() {};
	virtual void virt_pad_7() {};
	virtual void virt_pad_8() {};
	virtual void virt_pad_9() {};
	virtual void virt_pad_10() {};
	virtual void virt_pad_11() {};
	virtual void virt_pad_12() {};
	virtual void virt_pad_13() {};
	virtual void virt_pad_14() {};
	virtual void virt_pad_15() {};
	virtual void virt_pad_16() {};
	virtual void virt_pad_17() {};
	virtual void virt_pad_18() {};
	virtual void virt_pad_19() {};
	virtual void virt_pad_20() {};
	virtual void virt_pad_21() {};
	virtual void virt_pad_22() {};
	virtual void virt_pad_23() {};
	virtual void virt_pad_24() {};
	virtual void virt_pad_25() {};
	virtual void virt_pad_26() {};
	virtual void virt_pad_27() {};
	virtual void virt_pad_28() {};
	virtual void virt_pad_29() {};
	virtual void virt_pad_30() {};
	virtual void virt_pad_31() {};
	virtual void virt_pad_32() {};
	virtual void virt_pad_33() {};
	virtual void virt_pad_34() {};
	virtual void virt_pad_35() {};
	virtual void virt_pad_36() {};
	virtual void virt_pad_37() {};
	virtual void virt_pad_38() {};
	virtual void virt_pad_39() {};
	virtual void virt_pad_40() {};
	virtual void virt_pad_41() {};
	virtual void virt_pad_42() {};
	virtual void virt_pad_43() {};
	virtual void virt_pad_44() {};
	virtual void virt_pad_45() {};
	virtual void virt_pad_46() {};
	virtual void virt_pad_47() {};
	virtual void virt_pad_48() {};
	virtual void virt_pad_49() {};
	virtual void virt_pad_50() {};
	virtual void virt_pad_51() {};
	virtual void virt_pad_52() {};
	virtual void virt_pad_53() {};
	virtual void virt_pad_54() {};
	virtual void virt_pad_55() {};
	virtual void virt_pad_56() {};
	virtual void virt_pad_57() {};
	virtual void virt_pad_58() {};
	virtual void virt_pad_59() {};
	virtual void virt_pad_60() {};
	virtual void virt_pad_61() {};
	virtual void virt_pad_62() {};
	virtual void virt_pad_63() {};
	virtual void virt_pad_64() {};
	virtual void virt_pad_65() {};
	virtual void virt_pad_66() {};
	virtual void virt_pad_67() {};
	virtual void virt_pad_68() {};
	virtual void virt_pad_69() {};
	virtual void virt_pad_70() {};
	virtual void virt_pad_71() {};
	virtual void virt_pad_72() {};
	virtual void virt_pad_73() {};
	virtual void virt_pad_74() {};
	virtual void virt_pad_75() {};
	virtual void virt_pad_76() {};
	virtual void virt_pad_77() {};
	virtual void virt_pad_78() {};
	virtual void virt_pad_79() {};
	virtual void virt_pad_80() {};
	virtual void virt_pad_81() {};
	virtual void virt_pad_82() {};
	virtual void virt_pad_83() {};
	virtual void virt_pad_84() {};
	virtual void virt_pad_85() {};
	virtual void virt_pad_86() {};
	virtual void virt_pad_87() {};
	virtual void virt_pad_88() {};
	virtual void virt_pad_89() {};
	virtual void virt_pad_90() {};
	virtual void virt_pad_91() {};
	virtual void virt_pad_92() {};
	virtual void virt_pad_93() {};
	virtual void virt_pad_94() {};
	virtual void virt_pad_95() {};
	virtual void virt_pad_96() {};
	virtual void virt_pad_97() {};
	virtual void virt_pad_98() {};
	virtual void virt_pad_99() {};
	virtual void virt_pad_100() {};
	virtual void virt_pad_101() {};
	virtual void virt_pad_102() {};
	virtual void virt_pad_103() {};
	virtual void virt_pad_104() {};
	virtual void virt_pad_105() {};
	virtual void virt_pad_106() {};
	virtual void virt_pad_107() {};
	virtual void virt_pad_108() {};
	virtual void virt_pad_109() {};
	virtual void virt_pad_110() {};
	virtual void virt_pad_111() {};
	virtual void virt_pad_112() {};
	virtual void virt_pad_113() {};
	virtual void virt_pad_114() {};
	virtual void virt_pad_115() {};
	virtual void virt_pad_116() {};
	virtual void virt_pad_117() {};
	virtual void virt_pad_118() {};
	virtual void virt_pad_119() {};
	virtual void virt_pad_120() {};
	virtual void virt_pad_121() {};
	virtual void virt_pad_122() {};
	virtual void virt_pad_123() {};
	virtual void virt_pad_124() {};
	virtual void virt_pad_125() {};
	virtual void virt_pad_126() {};
	virtual void virt_pad_127() {};
	virtual void virt_pad_128() {};
	virtual void virt_pad_129() {};
	virtual void virt_pad_130() {};
	virtual void virt_pad_131() {};
	virtual void virt_pad_132() {};
	virtual void virt_pad_133() {};
	virtual void virt_pad_134() {};
	virtual void virt_pad_135() {};
	virtual void virt_pad_136() {};
	virtual void virt_pad_137() {};
	virtual void virt_pad_138() {};
	virtual void virt_pad_139() {};
	virtual void virt_pad_140() {};
	virtual void virt_pad_141() {};
	virtual void virt_pad_142() {};
	virtual void virt_pad_143() {};
	virtual void virt_pad_144() {};
	virtual void virt_pad_145() {};
	virtual void virt_pad_146() {};
	virtual void virt_pad_147() {};
	virtual void virt_pad_148() {};
	virtual void virt_pad_149() {};
	virtual void virt_pad_150() {};
	virtual void virt_pad_151() {};
	virtual void virt_pad_152() {};
	virtual void virt_pad_153() {};
	virtual void virt_pad_154() {};
	virtual void virt_pad_155() {};
	virtual void virt_pad_156() {};
	virtual void virt_pad_157() {};
	virtual void virt_pad_158() {};
	virtual void virt_pad_159() {};
	virtual void virt_pad_160() {};
	virtual auto getOptions() -> class Options* {};
	/* Functions */
};
#endif