#ifndef GUARD_Mob
#define GUARD_Mob
#include "../../Utils/Math.h"
#include "../../Utils/Utils.h"
#include "../../Mem/Mem.h"
#include "../../Utils/Nuv.h"
#include "Actor.h"
struct Mob : public Actor {
	/* Fields */
	char padding_1832[520];
	float yHeadRot;
	/* Virtuals */
	virtual void virt_pad_98() {};
	virtual void virt_pad_99() {};
	virtual void virt_pad_100() {};
	virtual void virt_pad_101() {};
	virtual void virt_pad_102() {};
	virtual void virt_pad_103() {};
	virtual void virt_pad_104() {};
	virtual void virt_pad_105() {};
	virtual void virt_pad_106() {};
	virtual void virt_pad_107() {};
	virtual void virt_pad_108() {};
	virtual void virt_pad_109() {};
	virtual void virt_pad_110() {};
	virtual void virt_pad_111() {};
	virtual void virt_pad_112() {};
	virtual void virt_pad_113() {};
	virtual void virt_pad_114() {};
	virtual void virt_pad_115() {};
	virtual void virt_pad_116() {};
	virtual void virt_pad_117() {};
	virtual void virt_pad_118() {};
	virtual void virt_pad_119() {};
	virtual void virt_pad_120() {};
	virtual void virt_pad_121() {};
	virtual void virt_pad_122() {};
	virtual void virt_pad_123() {};
	virtual void virt_pad_124() {};
	virtual void virt_pad_125() {};
	virtual void virt_pad_126() {};
	virtual void virt_pad_127() {};
	virtual void virt_pad_128() {};
	virtual void virt_pad_129() {};
	virtual void virt_pad_130() {};
	virtual void virt_pad_131() {};
	virtual void virt_pad_132() {};
	virtual void virt_pad_133() {};
	virtual void virt_pad_134() {};
	virtual void virt_pad_135() {};
	virtual void virt_pad_136() {};
	virtual void virt_pad_137() {};
	virtual void virt_pad_138() {};
	virtual void virt_pad_139() {};
	virtual void virt_pad_140() {};
	virtual void virt_pad_141() {};
	virtual void virt_pad_142() {};
	virtual void virt_pad_143() {};
	virtual void virt_pad_144() {};
	virtual void virt_pad_145() {};
	virtual void virt_pad_146() {};
	virtual void virt_pad_147() {};
	virtual void virt_pad_148() {};
	virtual void virt_pad_149() {};
	virtual void virt_pad_150() {};
	virtual void virt_pad_151() {};
	virtual void virt_pad_152() {};
	virtual void virt_pad_153() {};
	virtual void virt_pad_154() {};
	virtual void virt_pad_155() {};
	virtual void virt_pad_156() {};
	virtual void virt_pad_157() {};
	virtual void virt_pad_158() {};
	virtual void virt_pad_159() {};
	virtual void virt_pad_160() {};
	virtual void virt_pad_161() {};
	virtual void virt_pad_162() {};
	virtual void virt_pad_163() {};
	virtual void virt_pad_164() {};
	virtual void virt_pad_165() {};
	virtual void virt_pad_166() {};
	virtual void virt_pad_167() {};
	virtual void virt_pad_168() {};
	virtual void virt_pad_169() {};
	virtual void virt_pad_170() {};
	virtual void virt_pad_171() {};
	virtual void virt_pad_172() {};
	virtual void virt_pad_173() {};
	virtual void virt_pad_174() {};
	virtual void virt_pad_175() {};
	virtual void virt_pad_176() {};
	virtual void virt_pad_177() {};
	virtual void virt_pad_178() {};
	virtual void virt_pad_179() {};
	virtual void virt_pad_180() {};
	virtual void virt_pad_181() {};
	virtual void virt_pad_182() {};
	virtual void virt_pad_183() {};
	virtual void virt_pad_184() {};
	virtual void virt_pad_185() {};
	virtual void virt_pad_186() {};
	virtual void virt_pad_187() {};
	virtual void virt_pad_188() {};
	virtual void virt_pad_189() {};
	virtual void virt_pad_190() {};
	virtual void virt_pad_191() {};
	virtual void virt_pad_192() {};
	virtual void virt_pad_193() {};
	virtual void virt_pad_194() {};
	virtual void virt_pad_195() {};
	virtual void virt_pad_196() {};
	virtual void virt_pad_197() {};
	virtual void virt_pad_198() {};
	virtual void virt_pad_199() {};
	virtual void virt_pad_200() {};
	virtual void virt_pad_201() {};
	virtual void virt_pad_202() {};
	virtual void virt_pad_203() {};
	virtual void virt_pad_204() {};
	virtual void virt_pad_205() {};
	virtual void virt_pad_206() {};
	virtual void virt_pad_207() {};
	virtual void virt_pad_208() {};
	virtual void virt_pad_209() {};
	virtual void virt_pad_210() {};
	virtual void virt_pad_211() {};
	virtual void virt_pad_212() {};
	virtual void virt_pad_213() {};
	virtual auto swing() -> void {};
	/* Functions */
};
#endif